### PR TITLE
feat: add precommit hook

### PR DESCRIPTION
**Pull request by dammy001**

### CODE REVIEW

**Comment by productdevbook** [comment]
conflicting

**Comment by dammy001** [comment]
@productdevbook conflict resolved

**Comment by productdevbook** [comment]
Is it right to fix just before commit? What if it changes all the code we wrote?

**Comment by dammy001** [comment]
> Is it right to fix just before commit? What if it changes all the code we wrote?

I think applying a fix before committing is okay. No, it won't change the code we wrote since the same eslint config applies to all.

**Review by productdevbook — APPROVED** [review]

**Pull request merged**
