### PR TITLE
feat: slider component base

### LINKED ISSUE #21: Slider

### PR DESCRIPTION
**Pull request by Mushrr**
### Description

working with slider component

- [x] : feat: slider component base
- [x] : test: add test file and playground
- [ ] : wip: slider direction support. Currently, only horizontal sliders from left to right are supported.😀

### Linked Issues

close #21

### CODE REVIEW

**Comment by Mushrr** [comment]
I'm sorry, I forgot to submit the pnpm-lock. 😶‍🌫️

**Comment by productdevbook** [comment]
@Mushrr Hi, `useRef` and more change, can you take a look at the new structure and other components and update your codes here?

**Comment by productdevbook** [comment]
The new structure may cause you to change your tests, you should change your tests again according to the new structure.

**Comment by Mushrr** [comment]
@productdevbook OK, I will change my code in this weekend. The structures and components  I used currently  can not cover all scenarios, I am thinking how to fix this. Thanks😊

**Comment by productdevbook** [comment]
I'll be here to help you soon.

**Comment by productdevbook** [comment]
@Mushr I think you did the merge wrong, you better undo the last commit.

**Comment by productdevbook** [comment]
Wait one more day, I'll come to your place. Because many structures have been improved. Thanks for your effort :heart:

**Comment by Mushrr** [comment]
that couldn't be better for me. The sturture of current slider component also need resturct. thanks 🥺

**Comment by Mushrr** [comment]
I am currently fixing it.

**Pull request closed without merging**
