### PR TITLE
refactor(toggle): use useModel and delete defaultPressed & modelValue

### PR DESCRIPTION
**Pull request by YeSuX**

### CODE REVIEW

**Comment by productdevbook** [comment]
Let's keep this pr and discuss. @dammy001

**Comment by dammy001** [comment]
> Let's keep this pr and discuss. @dammy001 

Okay.

**Comment by YeSuX** [comment]
I think this is a problem of component design standards, not just limited to headless component libraries. The best solution is that we can refer to several well-known vue component libraries. Let's take a look at them:
	1.	Whether there is a `defaultValue` attribute
	2.	Whether it can be controlled by `modelValue` and `pressed` to control the state of the component
After understanding, we can discuss and then formulate a standard.

**Comment by productdevbook** [comment]
https://github.com/oku-ui/primitives/pull/295

With this pr, this structure has been dissolved.

**Pull request closed without merging**
