### PR TITLE
feat(select): select component

### PR DESCRIPTION
**Pull request by dammy001**

### CODE REVIEW

**Comment by productdevbook** [comment]
What is the situation has been waiting for a long time.

**Comment by dammy001** [comment]
> What is the situation has been waiting for a long time.

@productdevbook i'll send the stories this weekend

**Comment by productdevbook** [comment]
@Cr0zy07 Can you take it and work on it? It's been on hold for a long time. @dammy001 won't be available. Let's help him.

**Comment by productdevbook** [comment]
Since we are switching to SFC, the codes are being rewritten. Thank you works ❤️

**Pull request closed without merging**
