### PR TITLE
feat(toast): new component

### PR DESCRIPTION
**Pull request by Cr0zy07**
### Linked Issues
WIP #24 

### Additional context
Needs
- [x] #269

### CODE REVIEW

**Comment by productdevbook** [comment]
there was an update to the core see spelling in other components, if you apply similar spelling, you will work comfortably here

**Comment by Cr0zy07** [comment]
Hey @productdevbook, Could you please help me fix those errors and check if I applied the new changes correctly. TQ.

**Comment by productdevbook** [comment]
Yes, I will check them all and make the necessary adjustments today.

**Comment by productdevbook** [comment]
I'm done, can you check it out and start writing a storybook and test it, if you need help you can rewrite it. Thank you all code

**Comment by productdevbook** [comment]
The library gives errors in the stories, should I have a look at the errors?

**Comment by Cr0zy07** [comment]
Yes, I was trying to figure it out but I couldn't. So, I just pushed the stories until I found why the `branche inject`. is undefined.

**Comment by Cr0zy07** [comment]
Yes, I was trying to figure it out but I couldn't. So, I just pushed the stories until I found why the `branche inject`. is undefined.


I think the problem is that the `viewportRef` inside the `toast-viewport.ts` is always null or might be something else.

**Comment by productdevbook** [comment]
> I think the problem is that the `viewportRef` inside the `toast-viewport.ts` is always null or might be something else.

I fixed this error, now there is another error.

**Comment by Cr0zy07** [comment]
> > I think the problem is that the `viewportRef` inside the `toast-viewport.ts` is always null or might be something else.
> 
> I fixed this error, now there is another error.

Sorry, I was busy this weekend. I'm checking it now 😅>

**Comment by Cr0zy07** [comment]
It still has some issues:


The `Toast` is not open by default. Although, the `initialValue: true` is set inside the `useControllable`.

One/Two issue/s might be related to  `slots`.

And the `scheduler flush` issue, might be inside the `utilis` file.


I will try to fix them tonight...

**Comment by Cr0zy07** [comment]
Two issues remain

The toast does not rendered inside the `viewport`, and this is because the `Teleport` is set to the `body`, but as I understand the `getAnnounceTextContent` should move it to the viewport. I tried to set the `Teleport` to `ol` manually for testing and it seems that the `Toast` functionalities are working well. 


The second issue is the `component is missing templete or render function` warning.

**Comment by productdevbook** [comment]
Now Fixed 🚀, Thank you so much for everything. You are great. You're doing great.

**Review by productdevbook — APPROVED** [review]
You best 👍

**Pull request merged**
